language: node_js

node_js:
  - "5.11.1"

cache:
  - npm
  - apt

install:
  - bin/install

before_script:
  - npm install -g gulp

script:
  - cp .env-sample .env
  - bin/test

after_success:
  - zappa update production
